#!/bin/bash
export JNML_VERSION=0.4.0

export CLASSPATH=.:./target/jNeuroML-$JNML_VERSION-jar-with-dependencies.jar:$JNML_HOME/target/jNeuroML-$JNML_VERSION-jar-with-dependencies.jar

java -Xmx400M -classpath $CLASSPATH org.neuroml.JNeuroML $*
